groups:
  admin:
    permissions:
    - bukkit.command.gamemode.creative
    prefix: "§c[ADMIN] "
    suffix: "§f"
  default:
    permissions:
      - bukkit.command.gamemode.creative
    prefix: "§7"
    suffix: "§7"
users: